# Generated by Django 3.1.1 on 2020-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('facebook_link', models.URLField(max_length=100)),
                ('Twitter_link', models.URLField(max_length=100)),
                ('google_plus_link', models.URLField(max_length=100)),
            ],
        ),
    ]
